config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'pins#index'
  
  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end
  
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  acts_as_votable
  
  has_attached_file :image, styles: { :medium => "300x300>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :pins
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @pins = Pin.all.order("created_at DESC")
  end
  
  def show
  end
  
  def new
    @pin = current_user.pins.build
  end
  
  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      flash[:success] = "Pin created!"
      redirect_to @pin
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @pin.update(pin_params)
      flash[:success] = "Pin updated!"
      redirect_to @pin
    else
      render 'edit'
    end
  end
  
  def destroy
    @pin.destroy
    flash[:danger] = "Pin removed!"
      redirect_to root_path
  end
  
  def upvote
    @pin.upvote_by current_user
    flash[:success] = "Like saved!"
    redirect_to :back
  end
  
  
  private
    
    def pin_params
      params.require(:pin).permit(:title, :description, :image)
    end
    
    def find_pin
      @pin = Pin.find(params[:id])
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinterest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to "Pin Board", root_path %>
      </div>
        
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Add Pin", new_pin_path %></li>
            <li><%= link_to "Account", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Register", new_user_registration_path %></li>
            <li><%= link_to "Log In", new_user_session_path %></li>
          </ul>
        <% end %>
    </div>
  </nav>
  
  <div class="container">
    <% flash.each do |name, message| %>
      <%= content_tag :div, message, class: "alert alert-info" %>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
  <div id="errors">
    <h2>
      <%= pluralize(@pin.errors.count, "error") %> prevented this Pin from being saved!
    </h2>
    <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  
  <div class="form-group">
    <p>
      <%= f.input :image, input_html: { class: "form-control" } %><br>
      <%= f.input :title, input_html: { class: "form-control" } %><br>
      <%= f.input :description, input_html: { class: "form-control" } %>
    </p>
  </div>

    <p><%= f.button :submit, class: "btn btn-primary" %>
       <% if request.path.include?('edit')  %>
         <%= link_to "Cancel Edit", pin_path, class: "btn btn-primary" %>
       <% end %></p>
  
<% end %>  

app/views/pins/edit.html.erb
<div class="col-md-8 col-md-offset-2" id="edit_page">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Edit Pin</h1>
      </div>
      <div class="panel-body">
        <div class="current_image">
          <strong class="center"> Current Image
            <%= image_tag @pin.image.url(:medium) %>
          </strong>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">

  <% @pins.each do |p| %>
    <div class="box panel panel-default">
      <%= link_to (image_tag p.image.url), p %>
      <div class="panel-body">
        <h2><%= link_to p.title, p %></h2>
        <p class="user">
          Submitted by <%= p.user.email %>
        </p>
      </div>
      
    </div>
  <% end %>
  
</div>

app/views/pins/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Add Pin</h1>
        <div class="panel-body">
          <%= render 'form' %>
          <%= link_to "Back Home", root_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pins/show.html.erb
<div class="row" id="pin_show">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading pin_image">
        <%= image_tag @pin.image.url %>
      </div>
      <div class="panel-body">
        <h1>
          <%= @pin.title %>
        </h1>
        <p class="description">
          <%= @pin.description %>
        </p>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <p class="user">
              Submitted by <%= @pin.user.email %>
            </p>
          </div>
          <div class="col-md-6">
            <div class="btn-group pull-right">
                <%= link_to like_pin_path(@pin), method: :put,
                                                 class: "btn btn-default" do %>
                  <span class="glyphicon glyphicon-heart">
                    <%= @pin.get_upvotes.size %>
                  </span>
                <% end %>
                <% if user_signed_in? %>
                <%= link_to "Edit", edit_pin_path, class: "btn btn-default" %>
                <%= link_to "Delete", pin_path, method: :delete,
                                      data: { confirm: "Are you sure?" },
                                      class: "btn btn-default" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_form.html.erb
<%= simple_form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
  <div id="errors">
    <h2>
      <%= pluralize(@pin.errors.count, "error") %> prevented this Pin from being saved!
    </h2>
    <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  
  <div class="form-group">
    <p>
      <%= f.input :image, input_html: { class: "form-control" } %><br>
      <%= f.input :title, input_html: { class: "form-control" } %><br>
      <%= f.input :description, input_html: { class: "form-control" } %>
    </p>
  </div>

    <p><%= f.button :submit, class: "btn btn-primary" %>
       <% if current_page? edit_pin_path(@pin)  %>
         <%= link_to "Cancel Edit", pin_path, class: "btn btn-primary" %>
       <% end %></p>
  
<% end %>  